#!/bin/sh

cwd="$(basename "$(pwd)")"
category=$(echo "$cwd" | sed -r 's/(^|_)([a-z])/\1\U\2/g' | tr '_' ' ')

name="$(git config --get user.name)"
mail="$(git config --get user.email)"

cat - << END
---
title: ""
author: "$name ($mail)"
date: "$(date +"%Y-%m-%d")"
subject: "$category"
subtitle: "$category"
lang: "pl"
---
END
